import { describe, expect, it } from 'vitest';
import { applyOp, type EntityState } from '../ops/apply.ts';
import { makeOp } from '../ops/op.ts';
import { replay } from '../ops/replay.ts';
import { blockConfigSchema, MAX_QUANTITY } from '../schemas/block-config.ts';
import { templateRowSchema, type BlockRow, type JsonValue, type LocationRow } from '../schemas/entities.ts';
import { buildSnapshot, type RelatorioSnapshot } from '../schemas/snapshot.ts';
import { standardTemplate } from '../seed/template.ts';
import { idSequence, T0, TEST_COMPANY, TEST_PROJECT, TEST_USER } from '../test-support.ts';
import { instantiateTemplate } from '../relatorio/instantiate.ts';
import { locationBlocks } from '../relatorio/tree.ts';
import { templateFromRelatorio, templateSavedText } from './from-relatorio.ts';

const NEW_TEMPLATE = '019966b0-0060-7000-8000-000000000099';

function build(template = standardTemplate({ id: '019966b0-0060-7000-8000-000000000001' }), prefix = '019966b0-0061-7000-8000-') {
  const { relatorioId, drafts } = instantiateTemplate(
    template,
    { id: TEST_PROJECT },
    { service_start: null, service_end: null, existingEquipment: [], responsible_user_id: null },
    { newId: idSequence(prefix), actorId: TEST_USER, companyId: TEST_COMPANY },
  );
  const ops = drafts.map((d) => makeOp({ ...d, device_id: 'tablet-test' }, { newId: idSequence('019966b0-0062-7000-8000-'), now: T0 }));
  const state = replay(ops.map((op, i) => ({ ...op, seq: i + 1 })));
  return { relatorioId, state, snapshot: buildSnapshot(state, relatorioId) };
}

const putOp = (relatorioId: string, path: string, value: unknown, factory = idSequence('019966b0-0063-7000-8000-')) =>
  makeOp(
    { kind: 'put', scope: 'relatorio', company_id: TEST_COMPANY, project_id: null, relatorio_id: relatorioId, path, value: value as JsonValue, prev_op_id: null, batch_id: null, meta: null, actor_id: TEST_USER, device_id: 'tablet-test' },
    { newId: factory, now: T0 },
  );

/** Per location path in skeleton order: the block types and configs in order (what a relatório's structure is). */
function structure(snapshot: Pick<RelatorioSnapshot, 'locations' | 'blocks'>) {
  const live = snapshot.locations.filter((row) => row.removed_at === null);
  const nameOf = (row: LocationRow) => (row.parent_id === null ? row.name : `${live.find((p) => p.id === row.parent_id)!.name} › ${row.name}`);
  return [...live]
    .sort((a, b) => (a.order_key < b.order_key ? -1 : 1))
    .map((row) => ({
      path: nameOf(row),
      agrupar: row.kind === 'cabine' ? row.agrupar_por_tipo : null,
      blocks: locationBlocks(snapshot.blocks, row.id).map((block) => ({ type: block.block_type, config: blockConfigSchema.parse(block.config) })),
    }))
    .sort((a, b) => a.path.localeCompare(b.path));
}

describe('11.3-UNIT templateFromRelatorio over the standard relatório', () => {
  const { snapshot } = build();
  const template = templateFromRelatorio(snapshot, { id: NEW_TEMPLATE, name: 'Porto Seguro' });

  it('parses with templateRowSchema at version 1 on the relatório seed', () => {
    expect(templateRowSchema.parse(template)).toBeTruthy();
    expect(template).toMatchObject({ id: NEW_TEMPLATE, name: 'Porto Seguro', version: 1, seed_version: snapshot.relatorio.seed_version, archived_at: null, removed_at: null });
  });

  it('carries the cabines each followed by its colunas, 6 + 17 nodes', () => {
    expect(template.skeleton.filter((node) => node.kind === 'cabine')).toHaveLength(6);
    expect(template.skeleton.filter((node) => node.kind === 'coluna')).toHaveLength(17);
    const firstColuna = template.skeleton.findIndex((node) => node.kind === 'coluna');
    expect(template.skeleton[firstColuna - 1]!.kind).toBe('cabine');
  });

  it('merges runs of equal configs into quantities: 94 sheets in all, sections 7 and 9 never carried', () => {
    const equipment = template.blocks.filter((block) => block.skeleton_location_ref !== null);
    expect(equipment.reduce((sum, block) => sum + block.quantity, 0)).toBe(94);
    expect(equipment.length).toBeLessThan(94);
    const sections = template.blocks.filter((block) => block.skeleton_location_ref === null).map((block) => block.block_type);
    expect(sections).not.toContain('section_7');
    expect(sections).not.toContain('section_9');
    expect(sections).toHaveLength(9);
  });

  it('round-trips through instantiateTemplate: same skeleton, same types and configs per column in order', () => {
    const again = build(template, '019966b0-0064-7000-8000-');
    expect(structure(again.snapshot)).toEqual(structure(snapshot));
    // TAGs are regenerated by suggestTag, never carried.
    expect(again.snapshot.equipment.map((row) => row.tag).sort()).toEqual(snapshot.equipment.map((row) => row.tag).sort());
    expect(again.snapshot.equipment.every((row) => !snapshot.equipment.some((prior) => prior.id === row.id))).toBe(true);
  });
});

describe('11.3-UNIT what is carried and what is not', () => {
  it('skips removed blocks, removed sections and an orphan coluna; keeps agrupar, overrides and section text; no sheet data', () => {
    const { relatorioId, state } = build();
    let s: EntityState = state;
    const snap0 = buildSnapshot(s, relatorioId);
    const subsolo = snap0.locations.find((row) => row.name === '1° Subsolo')!;
    const coluna5 = snap0.locations.find((row) => row.name === 'Coluna 5')!;
    const col5Blocks = locationBlocks(snap0.blocks, coluna5.id);
    const [first, second] = col5Blocks;
    const section3 = snap0.blocks.find((row) => row.block_type === 'section_3')!;
    const section2 = snap0.blocks.find((row) => row.block_type === 'section_2')!;
    const enel = snap0.locations.find((row) => row.kind === 'cabine' && row.id !== subsolo.id)!;
    const factory = idSequence('019966b0-0065-7000-8000-');
    const override = blockConfigSchema.parse(first!.config);
    override.sub_blocks.nameplate = { enabled: false };
    const ops = [
      putOp(relatorioId, `location/${subsolo.id}/agrupar_por_tipo`, true, factory),
      putOp(relatorioId, `block/${first!.id}/config`, { ...override }, factory),
      putOp(relatorioId, `block/${section2.id}/config`, { ...(section2.config as object), section_text: 'Texto próprio {cliente}' }, factory),
      putOp(relatorioId, `block/${second!.id}/not_tested`, { reason: 'solicitacao_cliente', text: null, at: T0.toISOString(), by: TEST_USER }, factory),
      makeOp({ kind: 'remove', scope: 'relatorio', company_id: TEST_COMPANY, project_id: null, relatorio_id: relatorioId, path: `block/${section3.id}/removed_at`, value: null, prev_op_id: null, batch_id: null, meta: null, actor_id: TEST_USER, device_id: 'tablet-test' }, { newId: factory, now: T0 }),
    ];
    for (const op of ops) s = applyOp(s, op);
    const snapshot = buildSnapshot(s, relatorioId);
    // An orphan coluna (its cabine never on this device) and a removed block, fed directly.
    const orphan: LocationRow = { id: '019966b0-0066-7000-8000-000000000001', relatorio_id: relatorioId, parent_id: '019966b0-0066-7000-8000-000000000002', kind: 'coluna', name: 'Solta', order_key: 'a0', removed_at: null };
    const orphanBlock: BlockRow = { ...first!, id: '019966b0-0066-7000-8000-000000000003', location_id: orphan.id };
    const removedBlock: BlockRow = { ...first!, id: '019966b0-0066-7000-8000-000000000004', removed_at: T0.toISOString(), order_key: 'zz' };
    const template = templateFromRelatorio(
      { relatorio: snapshot.relatorio, locations: [...snapshot.locations, orphan], blocks: [...snapshot.blocks, orphanBlock, removedBlock] },
      { id: NEW_TEMPLATE, name: 'T' },
    );
    expect(templateRowSchema.safeParse(template).success).toBe(true);
    expect(template.skeleton.some((node) => node.ref === orphan.id)).toBe(false);
    expect(template.skeleton.find((node) => node.ref === subsolo.id)).toMatchObject({ kind: 'cabine', agrupar_por_tipo: true });
    expect(template.skeleton.find((node) => node.ref === enel.id)).toMatchObject({ agrupar_por_tipo: false });
    const sections = template.blocks.filter((block) => block.skeleton_location_ref === null);
    expect(sections.map((block) => block.block_type)).not.toContain('section_3');
    expect(sections.find((block) => block.block_type === 'section_2')!.section_text).toBe('Texto próprio {cliente}');
    const onCol5 = template.blocks.filter((block) => block.skeleton_location_ref === coluna5.id);
    expect(onCol5[0]!.sub_blocks.nameplate).toEqual({ enabled: false });
    expect(onCol5.reduce((sum, block) => sum + block.quantity, 0)).toBe(col5Blocks.length);
    // No data of the relatório in the row: no ids of equipment, blocks or tags.
    const text = JSON.stringify(template);
    for (const row of snapshot.equipment) {
      expect(text).not.toContain(row.id);
      expect(text).not.toContain(`"${row.tag}"`);
    }
    for (const block of snapshot.blocks) expect(text).not.toContain(block.id);
    expect(text).not.toContain('not_tested');
    expect(text).not.toContain('concluded_by');
    expect(text).not.toContain('solicitacao_cliente');
  });

  it('11.3-AFTER-MOVE: a block moved by a location_id put counts in its new column', () => {
    const { relatorioId, state } = build();
    const snap0 = buildSnapshot(state, relatorioId);
    const coluna5 = snap0.locations.find((row) => row.name === 'Coluna 5')!;
    const coluna9 = snap0.locations.find((row) => row.name === 'Coluna 9')!;
    const moved = locationBlocks(snap0.blocks, coluna5.id)[0]!;
    const count = (t: ReturnType<typeof templateFromRelatorio>, ref: string) => t.blocks.filter((block) => block.skeleton_location_ref === ref).reduce((sum, block) => sum + block.quantity, 0);
    const before = templateFromRelatorio(snap0, { id: NEW_TEMPLATE, name: 'T' });
    const after = buildSnapshot(applyOp(state, putOp(relatorioId, `block/${moved.id}/location_id`, coluna9.id)), relatorioId);
    const template = templateFromRelatorio(after, { id: NEW_TEMPLATE, name: 'T' });
    expect(count(template, coluna5.id)).toBe(count(before, coluna5.id) - 1);
    expect(count(template, coluna9.id)).toBe(count(before, coluna9.id) + 1);
  });

  it('splits a run longer than MAX_QUANTITY into 99 plus the rest, and still parses', () => {
    const { snapshot } = build();
    const coluna9 = snapshot.locations.find((row) => row.name === 'Coluna 9')!;
    const source = snapshot.blocks.find((row) => row.block_type === 'chave_seccionadora')!;
    const many: BlockRow[] = Array.from({ length: 101 }, (_, i) => ({
      ...source,
      id: `019966b0-0067-7000-8000-${i.toString(16).padStart(12, '0')}`,
      location_id: coluna9.id,
      order_key: `b${i.toString().padStart(3, '0')}`,
    }));
    const template = templateFromRelatorio({ relatorio: snapshot.relatorio, locations: snapshot.locations, blocks: [...snapshot.blocks, ...many] }, { id: NEW_TEMPLATE, name: 'T' });
    expect(template.blocks.filter((block) => block.skeleton_location_ref === coluna9.id).map((block) => block.quantity)).toEqual([MAX_QUANTITY, 2]);
    expect(templateRowSchema.safeParse(template).success).toBe(true);
  });

  it('templateSavedText', () => {
    expect(templateSavedText('Porto Seguro')).toBe('Template Porto Seguro salvo');
  });
});
