export { isConcurrent, mergeCell, mergePolicy, type MergeCellContext, type MergeOutcome, type MergePolicyInput } from './policy.ts';
export { mergeInfoOf, mergeInfoText, pulledAdditions, pulledMergePairs, type MergeInfo, type MergeInfoContext } from './info.ts';
export { MERGE_RULES, type MergeRule } from './rules.ts';
export {
  applyPickOps,
  conflictCellHeading,
  conflictOpIds,
  holdsConflictMarks,
  conflictPickLabel,
  conflictSideView,
  conflictValueText,
  conflictViewTitle,
  decisionBlockName,
  decisionCount,
  decisionKey,
  decisionText,
  keepBothTag,
  keptBothText,
  openDecisions,
  removalCardLines,
  removalColumnTitles,
  removalKeptText,
  removalRemovedText,
  type BlockRemovalDecision,
  type CellConflict,
  type CellDecision,
  type ConflictPick,
  type ConflictSideView,
  type Decision,
  type DecisionSide,
  type DecisionTextContext,
  type DuplicateTagDecision,
  type OpFacts,
  type OpenDecisionsInput,
} from './conflicts.ts';
export { stampSeen } from './stamp.ts';
