import { fileURLToPath } from 'node:url';
import { migrate as runMigrations } from 'drizzle-orm/postgres-js/migrator';
import type { Db } from './client.ts';

/** `apps/api/drizzle`: forward-only migrations generated by drizzle-kit. */
export const migrationsFolder = fileURLToPath(new URL('../../drizzle', import.meta.url));

/**
 * Applies every pending migration. Called once by the api at boot (before the
 * queue starts) and by the one-shot `migrate` compose service through
 * `migrate-cli.ts`; both are idempotent, so running one after the other is fine.
 */
export async function migrate(db: Db): Promise<void> {
  await runMigrations(db, { migrationsFolder });
}
