"""Deterministic generator of the synthetic transformer nameplate (Story 8.3).

Synthetic, no client material: the labels are the seed's pt-BR field labels of the
transformer nameplate (packages/domain/src/seed/v1.ts, instrumentTransformerFields('kVA')),
the values are invented. No randomness: the same image (Pillow, DejaVu fonts from
fonts-dejavu-core) gives the same JPEG bytes.

Writes, into the directory given as the first argument (default: this file's directory):
  plate-transformador.jpg          the plate, about 1600 x 1100, JPEG quality 90, no EXIF
  plate-transformador.tokens.json  {image: {width, height}, tokens: [{text, bbox}]}, one per
                                   printed word, bbox = Pillow textbbox, reading order
  plate-transformador.md           what the plate prints, the regenerate command, the sha256

Regenerate (inside the image, never on the host):
  docker compose --profile ocr run --rm --user "$(id -u):$(id -g)" \
    -v ./services/ocr/tests/fixtures:/app/tests/fixtures ocr python tests/fixtures/make_plate.py
"""

import hashlib
import json
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

NAME = "plate-transformador"
WIDTH, HEIGHT = 1600, 1100
BACKGROUND = (201, 204, 208)  # light metal grey
INK = (28, 30, 34)
FONT_DIR = Path("/usr/share/fonts/truetype/dejavu")
HEADER = "TRANSFORMADOR DE FORÇA"
HEADER_SIZE = 50
ROW_SIZE = 38
LABEL_X = 110
VALUE_X = 900
HEADER_Y = 70
FIRST_ROW_Y = 185
ROW_PITCH = 70

# (label as printed, value as printed, seed field key, seed field kind)
ROWS: list[tuple[str, str, str, str]] = [
    ("IDENTIFICAÇÃO", "TR-01", "identificacao", "text"),
    ("FABRICAÇÃO", "Celtta", "fabricacao", "manufacturer"),
    ("Nº SÉRIE", "240815-07", "n_serie", "text"),
    ("TIPO", "TSE-500/15", "tipo", "text"),
    ("TIPO DE ISOLAÇÃO", "EPÓXI", "tipo_de_isolacao", "select"),
    ("VOL. ÓLEO", "0 L", "vol_oleo", "number"),
    ("POTÊNCIA NOMINAL", "500 kVA", "potencia_nominal", "number"),
    ("TAP ATUAL", "3", "tap_atual", "text"),
    ("DATA FABRICAÇÃO", "08/2024", "data_fabricacao", "date"),
    ("TENSÃO NOMINAL AT", "15 kV", "tensao_nominal_at", "number"),
    ("TENSÃO NOMINAL BT", "380 V", "tensao_nominal_bt", "number"),
    ("LIGAÇÃO SECUNDÁRIA", "Dyn1", "ligacao_secundaria", "text"),
]


def value_words() -> list[str]:
    """The words of the right-hand values, in reading order."""
    return [w for _, value, _, _ in ROWS for w in value.split(" ")]


def _draw_words(draw: ImageDraw.ImageDraw, text: str, x: float, y: float, font) -> list[dict]:
    tokens = []
    space = font.getlength(" ")
    for word in text.split(" "):
        x = round(x)
        draw.text((x, y), word, font=font, fill=INK)
        x0, y0, x1, y1 = draw.textbbox((x, y), word, font=font)
        tokens.append({"text": word, "bbox": [x0, y0, x1, y1]})
        x += font.getlength(word) + space
    return tokens


def render() -> tuple[Image.Image, dict]:
    image = Image.new("RGB", (WIDTH, HEIGHT), BACKGROUND)
    draw = ImageDraw.Draw(image)
    draw.rectangle((30, 30, WIDTH - 31, HEIGHT - 31), outline=INK, width=6)
    bold = ImageFont.truetype(str(FONT_DIR / "DejaVuSans-Bold.ttf"), HEADER_SIZE)
    regular = ImageFont.truetype(str(FONT_DIR / "DejaVuSans.ttf"), ROW_SIZE)

    tokens = []
    header_x = (WIDTH - bold.getlength(HEADER)) / 2
    tokens += _draw_words(draw, HEADER, round(header_x), HEADER_Y, bold)
    draw.line((60, HEADER_Y + 80, WIDTH - 61, HEADER_Y + 80), fill=INK, width=3)
    for i, (label, value, _, _) in enumerate(ROWS):
        y = FIRST_ROW_Y + i * ROW_PITCH
        tokens += _draw_words(draw, label, LABEL_X, y, regular)
        tokens += _draw_words(draw, value, VALUE_X, y, regular)
    return image, {"image": {"width": WIDTH, "height": HEIGHT}, "tokens": tokens}


def _markdown(sha256: str) -> str:
    lines = [
        "# Fixture: synthetic transformer nameplate",
        "",
        "Synthetic test fixture of the OCR sidecar (Story 8.3). No client material: the labels",
        "are the seed's transformer nameplate labels, every value is invented.",
        "",
        "Generated by `make_plate.py` (Pillow, DejaVu Sans from `fonts-dejavu-core`, no randomness).",
        "Regenerate inside the image, never on the host:",
        "",
        "```",
        'docker compose --profile ocr run --rm --user "$(id -u):$(id -g)" \\',
        "  -v ./services/ocr/tests/fixtures:/app/tests/fixtures ocr python tests/fixtures/make_plate.py",
        "```",
        "",
        f"- Image: `{NAME}.jpg`, {WIDTH} x {HEIGHT}, JPEG quality 90, no EXIF",
        f"- sha256: `{sha256}`",
        f"- Expected tokens: `{NAME}.tokens.json` (one per printed word, Pillow `textbbox`, reading order)",
        "",
        f"Header line: `{HEADER}`.",
        "",
        "| Label | Value | Field key | Kind |",
        "|---|---|---|---|",
    ]
    lines += [f"| {label} | {value} | `{key}` | {kind} |" for label, value, key, kind in ROWS]
    lines += [
        "",
        "`Celtta` is absent from the seeded manufacturer registry and `15 kV` is the voltage.",
        "`VOL. ÓLEO 0 L` is a synthetic value chosen so every seed field prints one value.",
        "",
    ]
    return "\n".join(lines)


def write(out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    image, expected = render()
    jpg = out_dir / f"{NAME}.jpg"
    image.save(jpg, "JPEG", quality=90)
    (out_dir / f"{NAME}.tokens.json").write_text(json.dumps(expected, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    sha = hashlib.sha256(jpg.read_bytes()).hexdigest()
    (out_dir / f"{NAME}.md").write_text(_markdown(sha), encoding="utf-8")


if __name__ == "__main__":
    write(Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parent)
